#!/bin/bash

# usage: ./start <single config file> <local host:local port>

exec docker run \
    --rm \
    --tty \
    --interactive \
    --device=/dev/net/tun \
    --name=openvpn-client \
    --cap-add=NET_ADMIN \
    --publish $2:1984 \
    --volume "/etc/openvpn:/etc/openvpn/:ro" \
    --volume "$(realpath "$1"):/ovpn.conf:ro" \
    --sysctl net.ipv6.conf.all.disable_ipv6=1 \
    neoatlantis/openvpn-port-forwarding
